# This is a basic workflow to help you get started with Actions

name: Fetch data to file

# Controls when the action will run. 
on:
  workflow_dispatch:
  schedule:
    # Runs at 2 UTC everyday
    - cron: "0 2 * * *"


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Fetch Data to File
        uses: gautemo/fetch-api-data-action@1.0.2
        with:
          url: 'http://d-portal.org/dquery?sql=select%20count(aid)%20from%20act'
          file: 'backup/data.json'
